declare module "@drtrt/inject-file-fragments" {
    /**
     * Generates a file by injecting the content from one or more fragment files into a template.
     *
     * The path for each fragment should be included as part of the fragment placeholder within the template.
     *
     * For full detail, refer to the
     * {@link https://github.com/drtrt-org/inject-file-fragments#inject-file-fragments README}.
     * @param templateFilePath - The path to the template file.
     * @param generatedFilePath - The path to the file that is generated by injecting file fragments into the template.
     */
    function injectFileFragments(templateFilePath: string, generatedFilePath: string): void;

    export { injectFileFragments };
}
