# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Release

on:
    push:
        branches:
            - prep-for-publish

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: "18.x"
            - name: Release
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: npx semantic-release --dry-run
